//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComandaPreparat
    {
        public int id { get; set; }
        public int fk_comanda { get; set; }
        public int fk_preparat { get; set; }
        public int cantitate { get; set; }
    
        public virtual Comanda Comanda { get; set; }
        public virtual Preparat Preparat { get; set; }
    }
}
